# .yarnrc.yml - Yarn Berry (v2+) configuration
# Configuration for Yarn Berry (v2+) package manager

# =============================================================================
# CORE SETTINGS
# =============================================================================

# Yarn version to use (can be specific version or "stable", "latest", "canary")
yarnPath: .yarn/releases/yarn-3.6.0.cjs

# Node.js linker mode (node-modules, pnp, pnpm)
nodeLinker: node-modules

# Enable/disable PnP (Plug'n'Play)
pnpMode: loose

# =============================================================================
# REGISTRY SETTINGS
# =============================================================================

# Default registry
npmRegistryServer: "https://registry.npmjs.org"

# Unsafe HTTP registries (not recommended for production)
# unsafeHttpWhitelist:
#   - "*.company.internal"

# =============================================================================
# NETWORK SETTINGS
# =============================================================================

# HTTP timeout in milliseconds
httpTimeout: 60000

# HTTP retry settings
httpRetry: 3

# Proxy settings
# httpProxy: "http://proxy.company.com:8080"
# httpsProxy: "http://proxy.company.com:8080"

# =============================================================================
# CACHE SETTINGS
# =============================================================================

# Global cache folder
# cacheFolder: "~/.yarn/cache"

# Compression level for cache (0-9, where 0 is no compression)
compressionLevel: mixed

# Enable global cache
enableGlobalCache: true

# =============================================================================
# INSTALLATION BEHAVIOR
# =============================================================================

# Check files integrity
checksumBehavior: throw

# Default protocol for git dependencies
defaultProtocol: https

# Defer build of dependencies until needed
deferredVersionFolder: .yarn/versions

# Enable scripts
enableScripts: true

# Enable immutable installs (useful for CI)
# enableImmutableInstalls: true

# Enable inline builds
enableInlineBuilds: false

# =============================================================================
# TELEMETRY AND ANALYTICS
# =============================================================================

# Enable telemetry
enableTelemetry: false

# =============================================================================
# WORKSPACES
# =============================================================================

# Enable workspaces
# enableWorkspaces: true

# =============================================================================
# PLUGINS
# =============================================================================

# List of plugins to load
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

# =============================================================================
# PACKAGE EXTENSIONS
# =============================================================================

# Package extensions for fixing broken packages
packageExtensions:
  # Example: Add missing peer dependency
  # "package-name@*":
  #   peerDependencies:
  #     "missing-peer": "*"

# =============================================================================
# CONSTRAINTS
# =============================================================================

# Constraints engine (none, yarn)
constraintsPath: ./yarn.constraints.pro

# =============================================================================
# PNP SETTINGS (when using Plug'n'Play)
# =============================================================================

# PnP fallback mode
pnpFallbackMode: dependencies-only

# PnP ignore patterns
pnpIgnorePatterns:
  - "**/.git/**"
  - "**/node_modules/**"

# Enable PnP shims for better compatibility
pnpShebang: "#!/usr/bin/env node"

# =============================================================================
# LOGGING AND OUTPUT
# =============================================================================

# Log level (discard, error, warning, notice, info)
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

# Enable progress bars
enableProgressBars: true

# Preferred log format
preferInteractive: true

# =============================================================================
# SECURITY
# =============================================================================

# Enable network concurrency
networkConcurrency: 16

# Network settings for better security
supportedArchitectures:
  os:
    - current
  cpu:
    - current

# =============================================================================
# VERSION CONTROL
# =============================================================================

# Patterns for files that should be under version control
gitignorePatterns:
  - ".yarn/cache"
  - ".yarn/unplugged"
  - ".yarn/build-state.yml"
  - ".yarn/install-state.gz"
  - ".pnp.*"
# =============================================================================
# ENVIRONMENT VARIABLES
# =============================================================================

# Environment variables configuration
# enableStrictEnvironmentHandling: true

# =============================================================================
# NOTES
# =============================================================================

# This configuration is for Yarn Berry (v2+)
# For Yarn Classic (v1.x), use .yarnrc instead

# Key Yarn Berry features:
# 1. Zero-installs with committed dependencies
# 2. Plug'n'Play for faster module resolution
# 3. Workspaces with improved topology
# 4. Plugin architecture for extensibility
# 5. Constraints for workspace consistency

# Common Yarn Berry commands:
# yarn install                     # Install dependencies
# yarn add package-name            # Add dependency
# yarn dlx create-react-app        # Download and execute package
# yarn workspace workspace-name   # Run command in specific workspace
# yarn workspaces foreach          # Run command in all workspaces
# yarn plugin import              # Install plugin
# yarn constraints                # Check workspace constraints
# yarn dedupe                     # Remove duplicate dependencies

# To migrate from Yarn Classic to Berry:
# 1. Run: yarn set version stable
# 2. Update this configuration file
# 3. Run: yarn install
# 4. Commit .yarn/ directory changes

# For zero-installs setup:
# 1. Set nodeLinker to "pnp"
# 2. Commit .yarn/cache directory
# 3. Add .yarn/unplugged to .gitignore
# 4. Remove node_modules from version control
